# Generated by Django 5.1.2 on 2024-10-23 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0003_alter_studentmodel_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentmodel',
            name='address',
            field=models.TextField(null=True),
        ),
    ]
