# Generated by Django 5.1.2 on 2024-10-23 06:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0004_alter_studentmodel_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_date', models.DateField(null=True)),
                ('status', models.CharField(max_length=50)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_app.studentmodel')),
            ],
        ),
        migrations.CreateModel(
            name='LibraryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=10)),
                ('book_title', models.CharField(max_length=200)),
                ('return_date', models.DateField(blank=True, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_app.studentmodel')),
            ],
        ),
        migrations.CreateModel(
            name='OfficeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=254)),
                ('desigination', models.CharField(max_length=25)),
                ('subject', models.CharField(max_length=25)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_app.studentmodel')),
            ],
        ),
    ]
