# Generated by Django 5.1.2 on 2024-10-23 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0005_feesmodel_librarymodel_officemodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='officemodel',
            name='student',
        ),
    ]
