# Generated by Django 5.1.2 on 2024-10-23 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0006_remove_officemodel_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='officemodel',
            name='image',
            field=models.ImageField(default=1, upload_to='school_app/static'),
            preserve_default=False,
        ),
    ]
