# Generated by Django 5.1.2 on 2024-10-23 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0007_officemodel_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='officemodel',
            name='image',
        ),
    ]
