# Generated by Django 5.1.2 on 2024-10-23 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0008_remove_officemodel_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='librarymodel',
            name='book_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
