# Generated by Django 5.1.2 on 2024-10-24 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0010_alter_feesmodel_payment_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='officemodel',
            name='password',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
