# Generated by Django 5.1.2 on 2024-10-24 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0011_officemodel_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='librarymodel',
            name='stock',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
